const textData = {
  0: "",
  1: "<strong>Fecha de publicación:</strong> Marzo de 2024 </br>  <strong>Lugar:</strong> Estado Plurinacional de Bolivia</br> </br> <b>Institución responsable:</b> </br> Viceministerio de Educación Superior de Formación Profesional</br>Dirección General de Formación de Maestros</br>Unidad Especializada de Formación Continua – UNEFCO</br> </br> <b>Equipo de redacción y dirección:</b> </br>Fundación Ayuda en Acción </br> ProggettoMondo </br> Unidad Especializada de Formación Continua – UNEFCO </br> </br> <b>Créditos de las imágenes y flujogramas:</b> </br>Ilustraciones y dibujos: Fundación Ayuda en Acción; ProgettoMondo </br> Flujogramas: Fundación Ayuda en Acción </br>   </br> <b>Sitios oficiales:</b> </br> www.minedu.gob.bo </br> http://unefco.gob.bo/ </br> Bolivia, marzo, 2024  ",
  2: "Presiona los botones para navegar en el libro",
  3: "<br> <br> <br>  El Plan de Formación para Maestras y Maestros es una modalidad de aprendizaje, compuesta por cursos cortos, desarrollada por el Ministerio de Educación a través de la Unidad Especializada de Formación Continua (UNEFCO) para profundizar y fortalecer habilidades y capacidades en la labor educativa, con un enfoque en la mejora de las prácticas y procesos formativos. Su propósito, de acuerdo con la Ley de Educación N° 070 “Avelino Siñani – Elizardo Pérez”, es trabajar por la universalización del Modelo Educativo Sociocomunitario Productivo, en atención a los diferentes niveles y áreas temáticas, con relevancia cultural y lingüística. <br> <br> Las prácticas restaurativas se han venido consolidando como una ciencia social emergente desde aproximadamente el 2013, época en la cual se estudian las acciones individuales y efectivas dirigidas hacia tres objetivos: el fortalecimiento comunitario, la resolución pacífica de conflictos y la  del daño o falta u ofensa cuando se produce. Se definen las mismas como respuestas no punitivas orientadas a la reparación del daño, potenciar las relaciones interpersonales, fortalecer la resolución de los conflictos y desarrollar soluciones que incluyan a todas las personas involucradas en un daño o falta u ofensa; tomando en cuenta que el manejo restaurativo de los afectos en el aula mejora la capacidad para el aprendizaje y la resiliencia. <br> <br> Los cuadernos del ciclo formativo: <b> “PRÁCTICAS RESTAURATIVAS PARA LA RESOLUCIÓN DE CONFLICTOS Y UNA VIDA LIBRE DE VIOLENCIA” </b>, nos invitan a replantearnos la manera en que enfrentamos los conflictos, desafiando los paradigmas arraigados de confrontación y castigo. A medida que nos sumergimos en las profundidades de las prácticas restaurativas, descubrimos su capacidad no solo para restaurar el daño o falta u ofensa causado por los conflictos, sino también para fortalecer nuestros lazos comunitarios y fomentar un clima de confianza y respeto mutuo. Este ciclo cuenta con tres cursos, en el Primer Curso, se aborda la parte normativa, lo que es y no es conflicto para luego introducir al enfoque restaurativo; en el Segundo Curso, se presenta; y en el Tercer Curso presentamos una caja de herramientas práctica para la aplicación en el quehacer educativo. <br> <br><b> COORDINACIÓN GENERAL - UNEFCO",
  4: "<br><br>  <b>OBJETIVO HOLÍSTICO DEL CICLO</b> <br> <br>Desarrollamos procesos de <b>análisis y reflexión</b> sobre los <b>principios del enfoque restaurativo</b>, en la incorporación de las <b>prácticas restaurativas</b> en la <b>interacción educativa cotidiana</b>, a través de las decisiones de promoción de una <b>convivencia pacífica</b> y <b>libre de violencia educativa</b>, para que <b>maestras y maestros</b> sean los principales <b>actores en la resolución de conflictos</b>.  <br><br> <b>OBJETIVO HOLÍSTICO DEL CURSO</b> <br> <br> Reflexionamos sobre las <b>ventajas</b> de la aplicación del <b>enfoque restaurativo</b>, a través de las <b>prácticas restaurativas</b> para la <b>resolución de conflictos</b>, como <b>modelo facilitador</b> en las intervenciones restaurativas para la construcción de una <b>comunidad educativa</b> libre de <b>violencia</b> y con <b>cultura restaurativa</b>.  <br> ",
  5: "Tema 1",
  6: "<br> Para comenzar este <b>recorrido formativo</b>, te invitamos a participar en una <b>actividad de inicio</b> que tiene como objetivo <b>activar tus conocimientos previos</b> y generar una primera <b>reflexión</b> sobre los <b>temas centrales</b> que abordaremos en este módulo.  <br><br> Esta actividad está diseñada para ayudarte a <b>conectar tus experiencias</b> con los <b>conceptos</b> que se desarrollarán a lo largo del curso. A través de <b>preguntas clave</b>, <b>situaciones problematizadoras</b> o <b>ejercicios de análisis</b>, podrás identificar tus <b>percepciones iniciales</b> y abrir el <b>diálogo</b> con tus compañeras y compañeros.  <br><br> Recuerda <b>descargar la plantilla</b> Actividad de Inicio tema 1 o abrirla en la carpeta de <b>recursos adicionales</b> para llenar tus respuestas.  <br><br>",
  7: [
    "<br> <br> Como <b>maestras y maestros</b> es fundamental conocer las <b>normas de protección y prevención</b> referidas a la <b>resolución de conflictos</b> para una <b>vida sin violencia</b>; porque son <b>recursos importantes</b> que nos comprometen y vuelven <b>conscientes de nuestros derechos y obligaciones</b>. <br> <br> Además que nos orientan en el <b>abordaje y tratamiento</b> de esta temática dentro de nuestra <b>práctica educativa</b>.",
    "<b>CONVENCIÓN DE LOS DERECHOS DE LA NIÑEZ Y LA ADOLESCENCIA</b>  <br><br> La <b>normativa internacional</b> establece <b>criterios de protección</b> frente a situaciones de <b>conflicto en unidades educativas</b>.  <br> Estos <b>artículos</b> buscan proteger los <b>derechos</b> y el <b>bienestar</b> de los <b>niños, niñas y adolescentes</b> en contextos escolares, asegurando un <b>ambiente seguro</b> y propicio para su <b>desarrollo integral</b>.  <br> Es fundamental que las <b>unidades educativas</b> apliquen estas <b>disposiciones</b> para garantizar una <b>educación inclusiva</b> y <b>libre de violencia</b>. ",
  ],
  8: [
    "A nivel nacional, la niñez y adolescencia con base a diferentes normativas son protegidas en su integridad física, psicológica y sexual; en el sistema educativo.",
    "Maestras y maestros conocen la importancia de cuidar el interés superior de la niñez y adolescencia que guía su actuar ante una situación de violencia de no pares en el sistema educativo, por un lado; y por otro lado pueden actuar conforme a la normativa boliviana que respalda los derechos de sus estudiantes.",
  ],
  9: [
    "La normativa emitida por el Ministerio de Educación establece un marco. La <b> R. M. N° 001/2018 </b>, que regula las <b>normas generales para la gestión educativa y escolar </b>, así como la <b>R.M. N° 1204/2018</b>, que aborda la<b> prevención e intervención en casos de violencia entre pares o acoso escolar.</b>",
    "Por otro lado, la normativa más reciente <b> R.M. N° 0001/2024 </b> establece las <b> normas generales para la gestión educativa 2024. </b> Asimismo, la <b> R.M. N° 864/2019</b>, promulgada en agosto de 2019, presenta un <b>protocolo claro de prevención, actuación y denuncia.</b>",
  ],
  10: "<br> Este contenido, puede ser transmitido también a sus estudiantes, para que puedan comprender la importancia de sus derechos y su rol en el ejercicio; reconociéndose como sujetas y sujetos de derechos, que son parte de la protección y participación para la elaboración del Plan de Convivencia Pacífica y Armónica, y generar corresponsabilidad en las Rutas de Referencia y Contra referencia. <br> <br> Puedes encontrar el documento en la carpeta de recursos adicionales, escanear el QR o utilizar el botón. ",
  11: "<br>Esta actividad tiene como propósito invitarte a <b>  reconocer los distintos tipos de conflictos </b> que pueden surgir en el entorno educativo y reflexionar sobre cómo estos impactan en la convivencia escolar. A través de un ejercicio participativo, analizarás situaciones reales o hipotéticas y explorarás posibles respuestas desde un enfoque restaurativo. <br> <br> <b>  Te recomendamos realizar esta actividad de manera individual o grupal </b>, para compartir experiencias y enriquecer la comprensión colectiva del conflicto como oportunidad de aprendizaje. <br> <br>Recuerda <b> descargar la plantilla </b> Actividad sugerida tema 1 o abrirla en la carpeta de <b> recursos adicionales </b> para llenar tus respuestas.",
  12: "Tema 2",
  13: "<br>Iniciar un proceso de aprendizaje sobre convivencia y prácticas restaurativas requiere mirar hacia adentro y hacia nuestro entorno. Esta actividad busca generar un <b> espacio de reflexión personal y colectiva </b> sobre cómo entendemos el conflicto, cómo lo vivimos en la comunidad educativa y qué actitudes asumimos frente a él. <br> <br> A través de esta dinámica, podrás identificar tus percepciones, emociones y experiencias vinculadas al conflicto escolar, sentando así las bases para desarrollar una mirada más comprensiva, empática y transformadora.<br> <br> Recuerda <b> descargar la plantilla </b> Actividad de inicio tema 2 o abrirla en la carpeta de <b> recursos adicionales </b> para llenar tus respuestas.",
  14: "Para profundizar en el <b> Conflicto en el ámbito educativo</b>, utiliza las flechas para revisar más información, antes de continuar avanzando.",
  15: "",
  16: "",
  17: "",
  18: "Para profundizar en el <b> Conflicto entre personal docente</b>, utiliza las flechas para revisar más información, antes de continuar avanzando.",
  19: "",
  20: "Los conflictos en estudiantes de <b> primaria y secundaria</b>  pueden variar debido a las diferencias en su desarrollo cognitivo, emocional y social. Mientras que en la <b> educación primaria</b>  los desacuerdos suelen girar en torno a juegos, amistad y pertenencia, en la<b>  educación secundaria </b>  emergen conflictos más complejos relacionados con la identidad, la presión social o las relaciones afectivas.  A continuación, se tienen algunas de las diferencias clave:",
  21: "Para profundizar en los <b> Conflictos en la Comunidad Educativa</b>, utiliza las flechas para revisar más información, antes de continuar avanzando.",
  22: "",
  23: "La <b>violencia juvenil</b> está influenciada por diversos <b>factores de riesgo</b> que operan en diferentes niveles.  <br> <br> <b>    *    A nivel individual</b>, la <b>falta de empatía</b>, la <b>baja autoestima</b>, la <b>impulsividad</b> y el <b>consumo de sustancias</b> pueden aumentar la propensión a <b>conductas violentas</b>.  <br> <b>    *    En el ámbito familiar</b>, la <b>crianza autoritaria</b>, la <b>violencia doméstica</b> y la <b>falta de comunicación</b> pueden contribuir a estos comportamientos.  <br>  <b>    *    En el entorno escolar</b>, normas poco claras, la <b>falta de atención a la diversidad</b> y la <b>ausencia de metodologías adecuadas</b> generan un <b>clima propicio para la violencia</b>.  Además, la <b>comunidad</b> juega un papel clave, ya que la <b>pobreza</b>, la <b>falta de oportunidades económicas</b> y la <b>baja participación social</b> pueden agravar la situación.  <br> Comprender estos <b>factores</b> es esencial para diseñar <b>estrategias efectivas</b> de <b>prevención</b> y <b>atención</b>.   ",
  24: "",
  25: "Para fortalecer el análisis y la reflexión sobre la convivencia pacífica, la prevención de conflictos y la promoción de derechos en el contexto educativo, te invitamos a revisar la <b>  Ley Nº 548 - Código Niña, Niño y Adolescente </b>. Este importante marco normativo, aprobado en 2014, establece los derechos, garantías y deberes de niñas, niños y adolescentes en Bolivia, reconociéndolos como sujetos plenos de derechos. <br> <br> Su lectura permitirá comprender las bases legales que sustentan la intervención educativa frente a situaciones de violencia, el enfoque de protección integral y los principios rectores como el interés superior, la corresponsabilidad, la equidad de género y la participación.",
  26: [
    "La violencia se manifiesta de diversas formas y afecta la vida de las personas, impactando su bienestar emocional, físico y social. Comprender sus distintos tipos es fundamental para identificarla y prevenirla en cualquier contexto, especialmente en el ámbito educativo y comunitario.",
    "No todas las formas de violencia son evidentes o directas. En muchos casos, la omisión y la falta de protección pueden causar tanto daño como una agresión explícita. Por otro lado, la violencia sexual constituye una de las formas más graves de vulneración de derechos, ya que atenta contra la integridad, la dignidad y la seguridad de la persona. ",
  ],
  27: "Para profundizar en la <b> Resolución de conflictos</b>, utiliza las flechas para revisar más información, antes de continuar avanzando.",
  28: "",
  29: "Para construir una convivencia pacífica y resolver conflictos de manera efectiva, las prácticas restaurativas ofrecen diversas herramientas que fomentan el diálogo, la empatía y la responsabilidad. Estas estrategias permiten que las personas involucradas en un conflicto expresen sus emociones, reparen el daño causado y fortalezcan sus relaciones.",
  30: [
    "<br> La violencia en el sistema educativo puede manifestarse de múltiples formas, desde agresiones verbales y físicas hasta el acoso escolar, la exclusión social o la discriminación. Estas expresiones de violencia no solo afectan la convivencia diaria, sino que también inciden de manera negativa en el  bienestar emocional, el desarrollo personal y el rendimiento académico. Sin embargo, cuando se adopta un enfoque restaurativo, estas situaciones dejan de ser únicamente problemáticas y se convierten en oportunidades para el aprendizaje, la reflexión y la transformación positiva.",
    "A continuación, presentamos una tabla que asocia los tipos de violencia más comunes en el ámbito educativo con prácticas restaurativas sugeridas, permitiendo una intervención efectiva y adaptada a cada contexto. Estas estrategias fomentan el diálogo, la responsabilidad y la reparación del daño, promoviendo un ambiente de respeto y confianza en el entorno escolar.",
  ],
  31: "",
  32: "A través de esta actividad, reflexionarás sobre situaciones reales o hipotéticas que se presentan en el contexto escolar, explorando sus causas, efectos y posibles soluciones desde un enfoque restaurativo. <br> <br> El objetivo es desarrollar una mirada más profunda y crítica sobre el conflicto, reconociéndolo como parte de la experiencia humana y educativa, y entendiendo que su gestión adecuada puede fortalecer los vínculos entre los miembros de la comunidad. .<br> <br> Recuerda <b> descargar la plantilla </b> Actividad sugerida tema 2 o abrirla en la carpeta de <b> recursos adicionales </b> para llenar tus respuestas.",
  33: "Tema 3",
  34: "Esta actividad te invita a explorar cómo te relacionas con los demás, cómo participas en la convivencia diaria y qué aportes haces —o podrías hacer— para fortalecer un ambiente respetuoso, inclusivo y restaurativo. A través de esta dinámica, podrás identificar tus propias fortalezas y desafíos en la gestión de conflictos, así como reconocer el valor de tu participación en la construcción de relaciones positivas en el aula y en la escuela. .<br> <br> Recuerda <b> descargar la plantilla </b> Actividad de inicio de tema 3 o abrirla en la carpeta de <b> recursos adicionales </b> para llenar tus respuestas.",
  35: [
    "El enfoque de Derechos Humanos se constituye en un marco conceptual que busca contribuir al proceso de dey todos.sarrollo humano, además de orientar las acciones necesarias para dar cumplimiento a los derechos de las personas. Considera una serie de principios y ejes rectores que promueven la realización de todos los derechos como indivisibles e irrenunciables, articulados en tres grupos: derechos de supervivencia y desarrollo, derechos de protección, derechos de participación.",
    "Tomando en cuenta el ámbito normativo, este enfoque está basado en las disposiciones y estándares contenidos de los diferentes instrumentos internacionales de derechos humanos. Son el referente y fin último de las políticas públicas y estas, a su vez, son el instrumento o medio más idóneo para su realización <b>. implica realizar transformaciones sociales a partir del reconocimiento y análisis de las desigualdades  que se encuentran en el centro de los problemas del desarrollo </b>, a fin de corregir prácticas discriminatorias y el desigual reparto del poder que obstaculizan un desarrollo igual para todas.",
  ],
  36: "El enfoque restaurativo tiende a mirar <b> la resolución de problemas de manera colaborativa, brindando la oportunidad a las personas involucradas víctima y ofensora </b> ; en elaborar un plan para reparar daño causado. En el proceso, está involucradas ambas partes, porque permite generar empatía hacia la parte ofensora, comprendiendo la importancia de no repetir el daño; atendiendo así las necesidades de todas las personas involiucradas y restituyendo de esta forma el derecho a la víctima.  <br> <br> Vale decir, “... anima a la parte ofensora a responsabilizarse de sus acciones y del daño causado, a comprender las causas y efectos de su comportamiento en los otros; y a ofrecer soluciones que reparen el daño para merecer su reintegración en la comunidad, desde el reconocimiento que se juzgan los hechos y no al autor del delito” (Schmitz, El enfoque restaurativo para la construcción de paz desde la escuela, 2022). Por tanto,  <b> el enfoque restaurativo, es un camino para la construcción de la convivencia pacífica.</b>",
  37: "",
  38: "",
  39: [
    "<b>Enfoque punitivo dentro del sistema de disciplina y convivencia educativa  </b> <br><br> El comportamiento indebido, de parte del estudiante, es considerado como un acto que va en contra de la unidad educativa. Es una idea bastante abstracta. <br> <br>Para este tipo de administración de disciplina educativa quien comete un acto indebido debe recibir una sanción por el daño ocasionado. Es el pensamiento del “ojo por ojo, diente por diente <br> <br> <br> <br>",
    "<b>Enfoque restaurativo dentro del sistema de disciplina y convivencia educativa </b><br><br>El comportamiento indebido, por parte del estudiante, es un acto que va en contra de otra persona u otras personas, miembros de la comunidad educativa por lo que provoca una ruptura de las relaciones, afectando la convivencia en la unidad educativa. <br> <br> Este enfoque considera que, para la convivencia, es de vital importancia asumir responsabilidad, reparar los daños causados, restaurar el clima de convivencia que se vio afectado por la conducta indebida y siempre que se pueda lograr la reconciliación entre las partes en conflicto. <br><br> ",
  ],
  40: [
    "<b>Enfoque punitivo dentro del sistema de disciplina y convivencia educativa </b>  <br> <br> El enfoque punitivo se interesa únicamente por el hecho sucedido: ¿Por qué́ te comportaste de tal manera?, generando un sentimiento de culpa. <br>  Las personas responsables de la disciplina se enfocan en el error cometido: ¿Él o ella lo hizo? <br>  Lo que importa es la mala conducta, nada importa de saber lo que le ha llevado a comportarse de tal o cual manera.<br>",
    "<b> Enfoque restaurativo dentro del sistema de disciplina y convivencia educativa </b> <br><br> Si bien es importante que las personas responsables de la convivencia sepan lo que ha pasado, es fundamental interesarse en conocer por qué y pensar en el futuro.<br><br><br>",
  ],
  41: "",
  42: "",
  43: "Todos y cada uno de quienes conforman la comunidad educativa: estudiantes, maestras, maestros, administrativos, madres y padres de familia, deben y merecen ser valorados como personas, pero sobre todo con la posibilidad de generar ciudadanía y participación protagónica a través de los procesos de toma de decisiones dentro de un aula y escuela. <br><br> <b>  Cuando estudiantes sienten que una decisión que les afecta ha sido tomada de manera justa, confían y cooperan con el mundo adulto </b>, pero sobre todo con maestros y maestras, que tomaron una decisión. <br><br> Dicho proceso puede revelar la voluntad de una unidad educativa de confía r en el estamento estudiantil, y considerar sus ideas y experiencia o, por el contrario, rechazarlas, sin embargo, dentro de un marco de respeto y argumentación (Progettomondo.Mlal, EDUCO, FUDEP, 2018).",
  44: " En la <b> ventana de la disciplina social, muestra el estilo de autoridad que una persona asume. </b> La ventana de la disciplina social es un concepto que describe cuatro enfoques básicos para mantener las normas sociales y los límites conductuales. Puede ser aplicado al ámbito familiar como en el escolar. <br><br>  El modo en que se ejerce la autoridad en el aula influye directamente en la convivencia, el aprendizaje y el desarrollo socioemocional de los estudiantes. La ventana de la disciplina social nos permite analizar los diferentes estilos de autoridad según el nivel de firmeza, control y apoyo que brindan.",
  45: "Para profundizar en el <b> Dialogo restaurativo</b>, utiliza las flechas para revisar más información, antes de continuar avanzando.",
  46: "",
  47: "Esta actividad tiene como objetivo promover una mirada crítica y reflexiva sobre la evolución de los enfoques de atención a los conflictos y la violencia en las unidades educativas, desde el año 2000 hasta la actualidad. A través del trabajo colaborativo, maestras y maestros analizarán experiencias pasadas y presentes, compartirán vivencias, y construirán de forma creativa una línea de tiempo que represente los cambios, aprendizajes y desafíos enfrentados en estos 24 años. <br><br> El trabajo será socializado en plenaria, fomentando el intercambio de aprendizajes y el fortalecimiento del compromiso colectivo hacia una convivencia pacífica y armónica. <br><br>  Recuerda <b> descargar la plantilla </b> Actividad de inicio tema 2 o abrirla en la carpeta de <b> recursos adicionales </b> para llenar tus respuestas.",
  48: "<b>Comunidad Educativa</b>. Engloba a todos los miembros de la institución educativa, incluyendo estudiantes, directoras/es, maestras, maestros, personal administrativo y madres y padres de familias, que colaboran en la promoción de un ambiente de convivencia positiva.  <br><b>Círculos Restaurativos</b>. Son espacios donde se reúnen las partes involucradas en un conflicto, junto con un facilitador, para dialogar, expresar emociones y buscar acuerdos.  <br>  <b>Diálogo Restaurativo</b>. Consiste en promover conversaciones significativas y respetuosas entre las personas afectadas por un conflicto para buscar soluciones colaborativas.  <br>  <b>Escucha Activa</b>. Habilidad de prestar atención de manera consciente a lo que la otra persona está comunicando, fomentando la empatía y la comprensión mutua.  <br> <b>Enfoque restaurativo</b>. Es la forma de abordar una situación de conflicto o violencia, involucrando a ambas partes, para la atención de sus necesidades. Cuya característica principal, es la reparación de daño.  <br>  <b>Justicia Restaurativa</b>. Se refiere a un modelo de justicia que prioriza la reparación del daño causado y la restauración de las relaciones entre las partes involucradas.  <br>  <b>Prácticas Restaurativas</b>. Son un enfoque que busca gestionar conflictos de manera dialogada y participativa, involucrando a los afectados y a la comunidad en la resolución de problemas de comportamiento.  <br> <b>Prevención de Conflictos</b>. Estrategias y acciones destinadas a anticipar y evitar situaciones conflictivas, promoviendo la comunicación efectiva y el respeto mutuo.  ",
  49: "Bolivariano, I. E. (2023). Institución Educativa Bolivariano. <br> <br> Candia Moreno, Fernando (Coord). (1999). Diccionario de pedagogía y psicología. Madrid, España: Editorial Cultural. <br> <br> Educación, Ministerio de. (2022). Ciclo: Promoviendo la convivencia pacífica y armónica en las unidades educativas. Bolivia: Comunicación conceptual. <br> <br> Fernández, I. (2003). Escuela sin violencia: Resolución de conflictos. México: Grupo Editores Alfaomega. <br> <br> Hommes, T. d. (2018). Prevención de la violencia escolar y la convivencia pacífica. Guía práctica para desarrollar prácticas restaurativas en las instituciones educativas. Perú: Pixel Gráfico Impresores S.A.C. <br> <br> Informe de 2013. (2016). Promover la justicia restaurativa para las niñas, niños y adolescentes. New York, Estados Unidos: Oficina del Representante Especial del Secretario General sobre la violencia contra los niños. <br> <br> Paulero, R. (2021). Conflictos entre maestras y maestros y maestras y maestros y directivos de nivel primario. Representaciones, vivencias, comportamientos y consecuencias en la práctica docente. Revista Latinoamericana de Políticas y Administración de la Educación, 140–152.",

  50: "Progettomondo.Mlal, EDUCO, FUDEP. (2018). Prácticas restaurativas para la prevención y gestión de conflictos en el ámbito educativo. La Paz, Bolivia: Imprenta Cerro Azul S.R.L. <br> <br> Rodríguez, R. (2005). La acción tutorial para favorecer la convivencia: la disciplina. <br> <br> San Martín, J. A. (2003). La mediación escolar. Un camino para la gestión del conflicto escolar. Madrid, España. <br> <br> Schmitz, J. (2020). Prácticas restaurativas en el ámbito educativo. Ecuador. <br> <br> Terres des hommes. (2014). Auditoría Social de niños, niñas y adolescentes: ¿Es tiempo de derechos? Cochabamba, Bolivia: Kipus. <br> <br> UNEFCO. (2022). Ciclo: Promoviendo la convivencia pacífica y armónica en las unidades educativas. Tarija, Bolivia: UNEFCO. <br> <br>Vargas, G. (2019). Factores protectores y afrontamiento de riesgos asociados al uso de sustancias psicoactivas en adolescentes y jóvenes. La Paz, Bolivia: WA-GUI. <br> <br>Vasquez, Oscar. (2018). Guía práctica para desarrollar prácticas restaurativas en las instituciones educativas. Basada en la experiencia de la Fundación Terre des hommes en el Perú (2011–2017). Lima, Perú: Pixel Gráfico Impresores S.A.C.",
};
const titlesData = {
  0: "",
  1: "Curso 1: Enfoque restaurativo dentro del sistema educativo",
  2: "Contenido",
  3: "PRESENTACIÓN",
  4: "DATOS GENERALES DEL CUADERNO",
  5: "",
  6: "Primeras Miradas: ¿Qué entendemos por conflicto y restauración?",
  7: ["Base normativa", "Normativa internacional:"],
  8: ["Normativa nacional", "Ley 548 Codigo niño, niña, adolescente"],
  9: ["Ministerio de educación", "Esfuerzo institucional"],
  10: "Protocolo de prevención",
  11: "Reconociendo Conflictos y Caminos para la Convivencia",
  12: "",
  13: "Primeras Reflexiones sobre el Conflicto",
  14: "El conflicto en el ámbito educativo ",
  15: "Diferencia entre conflicto y problema",
  16: "El conflicto en el ámbito educativo",
  17: "Características del conflicto",
  18: "Conflictos entre personal docente y sus características ",
  19: "Conflictos entre estudiantes",
  20: "Los conflictos en estudiantes de primaria y secundaria",
  21: "Conflictos en la comunidad educativa y cómo gestionarlos",
  22: "Factores de riesgo en la unidad educativa",
  23: "Factores de riesgo considerando la violencia juvenil",
  24: "Violencia en el ámbito educativo",
  25: "",
  26: ["Glosario violencia", "Violencia por negligencia y violencia sexual"],
  27: "Resolución de conflictos en unidades educativas",
  28: "Para cada tipo de violencia hay una práctica restaurativa",
  29: "Herramientas para la practica restaurativa",
  30: [
    "Tipos de violencia y practicas restaurativas sugeridas",
    "Practicas restaurativas en ámbitos educativos",
  ],
  31: "Protagonismo estudiantil para la resolución de conflictos",
  32: "Diferencia entre conflicto y problema",
  33: "",
  34: "La importancia del enfoque restaurativo",
  35: [
    "Enfoque de derecho como base para el enfoque restaurativo",
    "Prácticas restaurativas",
  ],
  36: "Enfoque restaurativo",
  37: "Diferencias entre el enfoque restaurativo y punitivo en el ámbito educativo",
  38: "Comparación entre los enfoques punitivo y restaurativo",
  39: "Enfoque punitivo vs. Enfoque restaurativo",
  40: "Enfoque punitivo vs. Enfoque restaurativo",
  41: "Características y principios del enfoque restaurativo",
  42: "Enfoque restaurativo",
  43: "Proceso justo",
  44: "Ventana de la disciplina social y Estilos de autoridad",
  45: "Qué es el dialogo restaurativo",
  46: "Los afectos y la brújula de la vergüenza",
  47: "Línea de Tiempo de la Convivencia Escolar",
  48: "Glosario",
  49: "Bibliografía",
  50: "Bibliografía",
};
const layoutData = {
  0: "Alayout",
  1: "Blayout",
  2: "Clayout",
  3: "Blayout",
  4: "Dlayout",
  5: "Elayout",
  6: "Flayout",
  7: "Glayout",
  8: "Hlayout",
  9: "Hlayout",
  10: "Ilayout",
  11: "Flayout",
  12: "Elayout",
  13: "Flayout",
  14: "Jlayout",
  15: "Olayout",
  16: "Playout",
  17: "Playout",
  18: "Jlayout",
  19: "Dlayout",
  19: "Playout",
  20: "Llayout",
  21: "Jlayout",
  22: "Playout",
  23: "Llayout",
  24: "Olayout",
  25: "Ilayout",
  26: "Hlayout",
  27: "Jlayout",
  28: "Olayout",
  29: "Llayout",
  30: "Glayout",
  31: "Olayout",
  32: "Flayout",
  33: "Elayout",
  34: "Flayout",
  35: "Glayout",
  36: "Dlayout",
  37: "Olayout",
  38: "Olayout",
  39: "Nlayout",
  40: "Nlayout",
  41: "Olayout",
  42: "Olayout",
  43: "Dlayout",
  44: "Llayout",
  45: "Jlayout",
  46: "Playout",
  47: "Flayout",
  48: "Blayout",
  49: "Blayout",
  50: "Blayout",
};
const popUpData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: "Estructura del Ciclo",
      typeofContent: "image",
      contentModal: "PAG4POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: "Enfoque restaurativo dentro del sistema educativo",
      typeofContent: "image",
      contentModal: "PAG4POP-2.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: [
    {
      title: "CONVENCIÓN DE LOS DERECHOS DE​L NIÑO/A​ ",
      typeofContent: "image",
      contentModal: "PAG7POP-1.png",
      buttonName: "CONVENCIÓN DE LOS DERECHOS DE​L NIÑO/A​​ ",
    },
  ],
  8: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG8POP-1.png",
      buttonName: "Constitución Política del Estado ",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-2.png",
      buttonName: "Ley N° 070 deEducación",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-3.png",
      buttonName: "Ley N° 348",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-4.png",
      buttonName: "Ley N° 348 - Ámbito educativo",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-5.png",
      buttonName: "Ley N° 548",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-6.png",
      buttonName: "Ley N° 548 - Medidas preventivas",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-7.png",
      buttonName: "Ley N° 548 - Tipos de violencia",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-8.png",
      buttonName: "Ley N° 548 - Discriminación",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-9.png",
      buttonName: "Reglamento Ley N° 548: Referencia",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-10.png",
      buttonName: "Reglamento Ley N° 548: Plan de Convivencia",
    },
  ],
  9: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG9POP-1.png",
      buttonName: "Resolución Ministerial N° 001/2018 - Artículo 10 y 89 ",
    },

    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-3.png",
      buttonName: "Resolución Ministerial 1204/2018 - Artículo 3",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-4.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo III",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-5.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo IV",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-6.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo VI y VII",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-7.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 93 y 94",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-2.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 95 I y II",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-8.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 95 III",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-9.png",
      buttonName: "Resolución Ministerial N° 864/2019",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-10.png",
      buttonName: "Resolución Ministerial N° 864/2019",
    },
  ],
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG16POP-1.png",
      buttonName: "Abrir",
    },
  ],
  17: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG17POP-1.png",
      buttonName: "Abrir",
    },
  ],
  18: "",
  19: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG19POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG19POP-2.png",
      buttonName: "Abrir",
    },
  ],
  20: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-1.png",
      buttonName: "Relaciones Sociales",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-2.png",
      buttonName: "Independencia y Autonomia",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-3.png",
      buttonName: "Temas de conflicto",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-4.png",
      buttonName: "Comunicación",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-5.png",
      buttonName: "Normativa relacionada",
    },
  ],
  21: "",
  22: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG22POP-1.png",
      buttonName: "Abrir",
    },
  ],
  23: [
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-1.png",
      buttonName: "Individual",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-2.png",
      buttonName: "Familiar",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-3.png",
      buttonName: "Entre pares",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-4.png",
      buttonName: "Escolar",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-5.png",
      buttonName: "Comunidad",
    },
  ],
  24: "",
  25: "",
  26: [
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-1.png",
      buttonName: "Qué es la violencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-2.png",
      buttonName: "Qué es violencia psicologica - maltrato verbal",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-3.png",
      buttonName: "Qué es violencia psicologica - maltrato emocional",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-4.png",
      buttonName: "Qué es violencia físico",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-5.png",
      buttonName: "Qué es violencia físico - manifestaciones",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-6.png",
      buttonName: "Qué es violencia por negligencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-7.png",
      buttonName: "Qué es violencia por negligencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-8.png",
      buttonName: "Qué es la violencia sexual",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-9.png",
      buttonName: "Qué es la violencia sexual",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-10.png",
      buttonName: "Qué es la violencia sexual",
    },
  ],
  27: "",
  28: "",
  29: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-1.png",
      buttonName: "Declaraciones afectivas",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-2.png",
      buttonName: "Preguntas restaurativas",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-3.png",
      buttonName: "Pequeña reunión espontánea",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-4.png",
      buttonName: "Grupo o circulo",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-5.png",
      buttonName: "Reunión formal",
    },
  ],
  30: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG31POP-1.png",
      buttonName: "Práctica restaurativa sugerida",
    },
  ],
  31: "",
  32: "",
  33: "",
  34: "",
  35: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG36POP-1.png",
      buttonName:
        "¿Qué buscan las practicas restaurativas con enfoque de derechos humanos?",
    },
  ],
  36: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG37POP-1.png",
      buttonName: "Abrir",
    },
  ],
  37: "",
  38: "",
  39: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-1.png",
      buttonName: "N° 1",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-2.png",
      buttonName: "N° 2",
    },
  ],
  40: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-1.png",
      buttonName: "N° 3",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-2.png",
      buttonName: "N° 4",
    },
  ],
  41: "",
  42: "",
  43: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG44POP-1.png",
      buttonName: "Abrir",
    },
  ],
  44: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG45POP1.png",
      buttonName: "Ventana Social",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP1.png",
      buttonName: "Punitivo",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP2.png",
      buttonName: "Permisivo",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP3.png",
      buttonName: "Negligente",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP4.png",
      buttonName: "Restaurativo",
    },
  ],
  45: "",
  46: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG48POP1.png",
      buttonName: "Abrir",
    },
  ],
  47: "",
  48: "",
  49: "",
  50: "",
};
const popUp_xs_Data = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: "Estructura del Ciclo",
      typeofContent: "image",
      contentModal: "PAG4POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: "Enfoque restaurativo dentro del sistema educativo",
      typeofContent: "image",
      contentModal: "PAG4POP-2.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: [
    {
      title: "CONVENCIÓN DE LOS DERECHOS DE​L NIÑO/A​ ",
      typeofContent: "image",
      contentModal: "PAG7POP-1.png",
      buttonName: "CONVENCIÓN DE LOS DERECHOS DE​L NIÑO/A​​ ",
    },
  ],
  8: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG8POP-1.png",
      buttonName: "Constitución Política del Estado ",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-2.png",
      buttonName: "Ley N° 070 deEducación",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-3.png",
      buttonName: "Ley N° 348",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-4.png",
      buttonName: "Ley N° 348 - Ámbito educativo",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-5.png",
      buttonName: "Ley N° 548",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-6.png",
      buttonName: "Ley N° 548 - Medidas preventivas",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-7.png",
      buttonName: "Ley N° 548 - Tipos de violencia",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-8.png",
      buttonName: "Ley N° 548 - Discriminación",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-9.png",
      buttonName: "Reglamento Ley N° 548: Referencia",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-10.png",
      buttonName: "Reglamento Ley N° 548: Plan de Convivencia",
    },
  ],
  9: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG9POP-1.png",
      buttonName: "Resolución Ministerial N° 001/2018 - Artículo 10 y 89 ",
    },

    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-3.png",
      buttonName: "Resolución Ministerial 1204/2018 - Artículo 3",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-4.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo III",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-5.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo IV",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-6.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo VI y VII",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-7.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 93 y 94",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-2.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 95 I y II",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-8.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 95 III",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-9.png",
      buttonName: "Resolución Ministerial N° 864/2019",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-10.png",
      buttonName: "Resolución Ministerial N° 864/2019",
    },
  ],
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG16POP-1.png",
      buttonName: "Abrir",
    },
  ],
  17: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG17POP-1.png",
      buttonName: "Abrir",
    },
  ],
  18: "",
  19: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG19POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG19POP-2.png",
      buttonName: "Abrir",
    },
  ],
  20: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-1.png",
      buttonName: "Relaciones Sociales",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-2.png",
      buttonName: "Independencia y Autonomia",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-3.png",
      buttonName: "Temas de conflicto",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-4.png",
      buttonName: "Comunicación",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-5.png",
      buttonName: "Normativa relacionada",
    },
  ],
  21: "",
  22: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG22POP-1.png",
      buttonName: "Abrir",
    },
  ],
  23: [
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-1.png",
      buttonName: "Individual",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-2.png",
      buttonName: "Familiar",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-3.png",
      buttonName: "Entre pares",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-4.png",
      buttonName: "Escolar",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-5.png",
      buttonName: "Comunidad",
    },
  ],
  24: "",
  25: "",
  26: [
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-1.png",
      buttonName: "Qué es la violencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-2.png",
      buttonName: "Qué es violencia psicologica - maltrato verbal",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-3.png",
      buttonName: "Qué es violencia psicologica - maltrato emocional",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-4.png",
      buttonName: "Qué es violencia físico",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-5.png",
      buttonName: "Qué es violencia físico - manifestaciones",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-6.png",
      buttonName: "Qué es violencia por negligencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-7.png",
      buttonName: "Qué es violencia por negligencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-8.png",
      buttonName: "Qué es la violencia sexual",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-9.png",
      buttonName: "Qué es la violencia sexual",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-10.png",
      buttonName: "Qué es la violencia sexual",
    },
  ],
  27: "",
  28: "",
  29: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-1.png",
      buttonName: "Declaraciones afectivas",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-2.png",
      buttonName: "Preguntas restaurativas",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-3.png",
      buttonName: "Pequeña reunión espontánea",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-4.png",
      buttonName: "Grupo o circulo",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-5.png",
      buttonName: "Reunión formal",
    },
  ],
  30: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG31POP-1.png",
      buttonName: "Práctica restaurativa sugerida",
    },
  ],
  31: "",
  32: "",
  33: "",
  34: "",
  35: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG36POP-1.png",
      buttonName:
        "¿Qué buscan las practicas restaurativas con enfoque de derechos humanos?",
    },
  ],
  36: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG37POP-1.png",
      buttonName: "Abrir",
    },
  ],
  37: "",
  38: "",
  39: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-1.png",
      buttonName: "N° 1",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-2.png",
      buttonName: "N° 2",
    },
  ],
  40: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-1.png",
      buttonName: "N° 3",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-2.png",
      buttonName: "N° 4",
    },
  ],
  41: "",
  42: "",
  43: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG44POP-1.png",
      buttonName: "Abrir",
    },
  ],
  44: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG45POP1.png",
      buttonName: "Ventana Social",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP1.png",
      buttonName: "Punitivo",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP2.png",
      buttonName: "Permisivo",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP3.png",
      buttonName: "Negligente",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP4.png",
      buttonName: "Restaurativo",
    },
  ],
  45: "",
  46: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG48POP1.png",
      buttonName: "Abrir",
    },
  ],
  47: "",
  48: "",
  49: "",
  50: "",
};
const popUp_sm_Data = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: "Estructura del Ciclo",
      typeofContent: "image",
      contentModal: "PAG4POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: "Enfoque restaurativo dentro del sistema educativo",
      typeofContent: "image",
      contentModal: "PAG4POP-2.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: [
    {
      title: "CONVENCIÓN DE LOS DERECHOS DE​L NIÑO/A​ ",
      typeofContent: "image",
      contentModal: "PAG7POP-1.png",
      buttonName: "CONVENCIÓN DE LOS DERECHOS DE​L NIÑO/A​​ ",
    },
  ],
  8: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG8POP-1.png",
      buttonName: "Constitución Política del Estado ",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-2.png",
      buttonName: "Ley N° 070 deEducación",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-3.png",
      buttonName: "Ley N° 348",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-4.png",
      buttonName: "Ley N° 348 - Ámbito educativo",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-5.png",
      buttonName: "Ley N° 548",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-6.png",
      buttonName: "Ley N° 548 - Medidas preventivas",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-7.png",
      buttonName: "Ley N° 548 - Tipos de violencia",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-8.png",
      buttonName: "Ley N° 548 - Discriminación",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-9.png",
      buttonName: "Reglamento Ley N° 548: Referencia",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-10.png",
      buttonName: "Reglamento Ley N° 548: Plan de Convivencia",
    },
  ],
  9: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG9POP-1.png",
      buttonName: "Resolución Ministerial N° 001/2018 - Artículo 10 y 89 ",
    },

    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-3.png",
      buttonName: "Resolución Ministerial 1204/2018 - Artículo 3",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-4.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo III",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-5.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo IV",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-6.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo VI y VII",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-7.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 93 y 94",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-2.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 95 I y II",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-8.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 95 III",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-9.png",
      buttonName: "Resolución Ministerial N° 864/2019",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-10.png",
      buttonName: "Resolución Ministerial N° 864/2019",
    },
  ],
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG16POP-1.png",
      buttonName: "Abrir",
    },
  ],
  17: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG17POP-1.png",
      buttonName: "Abrir",
    },
  ],
  18: "",
  19: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG19POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG19POP-2.png",
      buttonName: "Abrir",
    },
  ],
  20: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-1.png",
      buttonName: "Relaciones Sociales",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-2.png",
      buttonName: "Independencia y Autonomia",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-3.png",
      buttonName: "Temas de conflicto",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-4.png",
      buttonName: "Comunicación",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-5.png",
      buttonName: "Normativa relacionada",
    },
  ],
  21: "",
  22: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG22POP-1.png",
      buttonName: "Abrir",
    },
  ],
  23: [
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-1.png",
      buttonName: "Individual",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-2.png",
      buttonName: "Familiar",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-3.png",
      buttonName: "Entre pares",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-4.png",
      buttonName: "Escolar",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-5.png",
      buttonName: "Comunidad",
    },
  ],
  24: "",
  25: "",
  26: [
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-1.png",
      buttonName: "Qué es la violencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-2.png",
      buttonName: "Qué es violencia psicologica - maltrato verbal",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-3.png",
      buttonName: "Qué es violencia psicologica - maltrato emocional",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-4.png",
      buttonName: "Qué es violencia físico",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-5.png",
      buttonName: "Qué es violencia físico - manifestaciones",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-6.png",
      buttonName: "Qué es violencia por negligencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-7.png",
      buttonName: "Qué es violencia por negligencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-8.png",
      buttonName: "Qué es la violencia sexual",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-9.png",
      buttonName: "Qué es la violencia sexual",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-10.png",
      buttonName: "Qué es la violencia sexual",
    },
  ],
  27: "",
  28: "",
  29: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-1.png",
      buttonName: "Declaraciones afectivas",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-2.png",
      buttonName: "Preguntas restaurativas",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-3.png",
      buttonName: "Pequeña reunión espontánea",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-4.png",
      buttonName: "Grupo o circulo",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-5.png",
      buttonName: "Reunión formal",
    },
  ],
  30: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG31POP-1.png",
      buttonName: "Práctica restaurativa sugerida",
    },
  ],
  31: "",
  32: "",
  33: "",
  34: "",
  35: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG36POP-1.png",
      buttonName:
        "¿Qué buscan las practicas restaurativas con enfoque de derechos humanos?",
    },
  ],
  36: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG37POP-1.png",
      buttonName: "Abrir",
    },
  ],
  37: "",
  38: "",
  39: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-1.png",
      buttonName: "N° 1",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-2.png",
      buttonName: "N° 2",
    },
  ],
  40: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-1.png",
      buttonName: "N° 3",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-2.png",
      buttonName: "N° 4",
    },
  ],
  41: "",
  42: "",
  43: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG44POP-1.png",
      buttonName: "Abrir",
    },
  ],
  44: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG45POP1.png",
      buttonName: "Ventana Social",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP1.png",
      buttonName: "Punitivo",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP2.png",
      buttonName: "Permisivo",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP3.png",
      buttonName: "Negligente",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP4.png",
      buttonName: "Restaurativo",
    },
  ],
  45: "",
  46: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG48POP1.png",
      buttonName: "Abrir",
    },
  ],
  47: "",
  48: "",
  49: "",
  50: "",
};
const popUp_md_Data = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: "Estructura del Ciclo",
      typeofContent: "image",
      contentModal: "PAG4POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: "Enfoque restaurativo dentro del sistema educativo",
      typeofContent: "image",
      contentModal: "PAG4POP-2.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: [
    {
      title: "CONVENCIÓN DE LOS DERECHOS DE​L NIÑO/A​ ",
      typeofContent: "image",
      contentModal: "PAG7POP-1.png",
      buttonName: "CONVENCIÓN DE LOS DERECHOS DE​L NIÑO/A​​ ",
    },
  ],
  8: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG8POP-1.png",
      buttonName: "Constitución Política del Estado ",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-2.png",
      buttonName: "Ley N° 070 deEducación",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-3.png",
      buttonName: "Ley N° 348",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-4.png",
      buttonName: "Ley N° 348 - Ámbito educativo",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-5.png",
      buttonName: "Ley N° 548",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-6.png",
      buttonName: "Ley N° 548 - Medidas preventivas",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-7.png",
      buttonName: "Ley N° 548 - Tipos de violencia",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-8.png",
      buttonName: "Ley N° 548 - Discriminación",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-9.png",
      buttonName: "Reglamento Ley N° 548: Referencia",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG8POP-10.png",
      buttonName: "Reglamento Ley N° 548: Plan de Convivencia",
    },
  ],
  9: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG9POP-1.png",
      buttonName: "Resolución Ministerial N° 001/2018 - Artículo 10 y 89 ",
    },

    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-3.png",
      buttonName: "Resolución Ministerial 1204/2018 - Artículo 3",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-4.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo III",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-5.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo IV",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-6.png",
      buttonName: "Resolución Ministerial 1204/2018 - Parrafo VI y VII",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-7.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 93 y 94",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-2.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 95 I y II",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-8.png",
      buttonName: "Resolución Ministerial N° 0001/2024 - Artículo 95 III",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-9.png",
      buttonName: "Resolución Ministerial N° 864/2019",
    },
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG9POP-10.png",
      buttonName: "Resolución Ministerial N° 864/2019",
    },
  ],
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG16POP-1.png",
      buttonName: "Abrir",
    },
  ],
  17: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG17POP-1.png",
      buttonName: "Abrir",
    },
  ],
  18: "",
  19: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG19POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG19POP-2.png",
      buttonName: "Abrir",
    },
  ],
  20: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-1.png",
      buttonName: "Relaciones Sociales",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-2.png",
      buttonName: "Independencia y Autonomia",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-3.png",
      buttonName: "Temas de conflicto",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-4.png",
      buttonName: "Comunicación",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG20POP-5.png",
      buttonName: "Normativa relacionada",
    },
  ],
  21: "",
  22: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG22POP-1.png",
      buttonName: "Abrir",
    },
  ],
  23: [
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-1.png",
      buttonName: "Individual",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-2.png",
      buttonName: "Familiar",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-3.png",
      buttonName: "Entre pares",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-4.png",
      buttonName: "Escolar",
    },
    {
      title: "Factores de Riesgo",
      typeofContent: "image",
      contentModal: "PAG23POP-5.png",
      buttonName: "Comunidad",
    },
  ],
  24: "",
  25: "",
  26: [
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-1.png",
      buttonName: "Qué es la violencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-2.png",
      buttonName: "Qué es violencia psicologica - maltrato verbal",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-3.png",
      buttonName: "Qué es violencia psicologica - maltrato emocional",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-4.png",
      buttonName: "Qué es violencia físico",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-5.png",
      buttonName: "Qué es violencia físico - manifestaciones",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-6.png",
      buttonName: "Qué es violencia por negligencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-7.png",
      buttonName: "Qué es violencia por negligencia",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-8.png",
      buttonName: "Qué es la violencia sexual",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-9.png",
      buttonName: "Qué es la violencia sexual",
    },
    {
      title: "Definición",
      typeofContent: "image",
      contentModal: "PAG26POP-10.png",
      buttonName: "Qué es la violencia sexual",
    },
  ],
  27: "",
  28: "",
  29: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-1.png",
      buttonName: "Declaraciones afectivas",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-2.png",
      buttonName: "Preguntas restaurativas",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-3.png",
      buttonName: "Pequeña reunión espontánea",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-4.png",
      buttonName: "Grupo o circulo",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-5.png",
      buttonName: "Reunión formal",
    },
  ],
  30: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG31POP-1.png",
      buttonName: "Práctica restaurativa sugerida",
    },
  ],
  31: "",
  32: "",
  33: "",
  34: "",
  35: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG36POP-1.png",
      buttonName:
        "¿Qué buscan las practicas restaurativas con enfoque de derechos humanos?",
    },
  ],
  36: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG37POP-1.png",
      buttonName: "Abrir",
    },
  ],
  37: "",
  38: "",
  39: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-1.png",
      buttonName: "N° 1",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-2.png",
      buttonName: "N° 2",
    },
  ],
  40: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-1.png",
      buttonName: "N° 3",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-2.png",
      buttonName: "N° 4",
    },
  ],
  41: "",
  42: "",
  43: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG44POP-1.png",
      buttonName: "Abrir",
    },
  ],
  44: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG45POP1.png",
      buttonName: "Ventana Social",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP1.png",
      buttonName: "Punitivo",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP2.png",
      buttonName: "Permisivo",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP3.png",
      buttonName: "Negligente",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG46POP4.png",
      buttonName: "Restaurativo",
    },
  ],
  45: "",
  46: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG48POP1.png",
      buttonName: "Abrir",
    },
  ],
  47: "",
  48: "",
  49: "",
  50: "",
};
const images_xs_Data = {
  1: "",
  2: "",
  3: "",
  4: "PAG4-1_XS.png",
  5: "PAG5-1_XS.png",
  6: ["PAG6-1_XS.png", "PAG6-2_XS.png"],
  7: "",
  8: "",
  9: "",
  10: ["PAG10-1_XS.png", "PAG10-2_XS.png"],
  11: ["PAG11-1_XS.png", "PAG11-2_XS.png"],
  12: "PAG12-1_XS.png",
  13: ["PAG13-1_XS.png", "PAG13-2_XS.png"],
  14: [
    "PAG14-1_XS.png",
    "PAG14-2_XS.png",
    "PAG14-3_XS.png",
    "PAG14-4_XS.png",
    "PAG14-5_XS.png",
  ],
  15: "PAG15-1_XS.png",
  16: "PAG16-1_XS.png",
  17: "PAG17-1_XS.png",
  18: ["PAG18-1_XS.png", "PAG18-2_XS.png", "PAG18-3_XS.png", "PAG18-4_XS.png"],
  19: "PAG19-1_XS.png",
  20: " ",
  21: [
    "PAG21-1_XS.png",
    "PAG21-2_XS.png",
    "PAG21-3_XS.png",
    "PAG21-4_XS.png",
    "PAG21-5_XS.png",
  ],
  22: "PAG22-1_XS.png",
  23: " ",
  24: "PAG24-1_XS.png",
  25: ["PAG25-1_XS.png", "PAG25-2_XS.png"],
  26: " ",
  27: [
    "PAG27-1_XS.png",
    "PAG27-2_XS.png",
    "PAG27-3_XS.png",
    "PAG27-4_XS.png",
    "PAG27-5_XS.png",
  ],
  28: "PAG28-1_XS.png ",
  29: " ",
  30: " ",
  31: "PAG31-1_XS.png",
  32: ["PAG33-1_XS.png", "PAG33-2_XS.png"],
  33: "PAG34-1_XS.png",
  34: ["PAG35-1_XS.png", "PAG35-2_XS.png"],
  35: " ",
  36: "PAG36-1_XS.png",
  37: "PAG37-1_XS.png ",
  38: "PAG38-1_XS.png ",
  39: "",
  40: "",
  41: "PAG41-1_XS.png",
  42: "PAG42-1_XS.png",
  43: "PAG44-1_XS.png",
  44: "",
  45: [
    "PAG47-1_XS.png",
    "PAG47-2_XS.png",
    "PAG47-3_XS.png",
    "PAG47-4_XS.png",
    "PAG47-5_XS.png",
  ],
  46: "PAG46-1_XS.png",
  47: ["PAG49-1_XS.png", "PAG49-2_XS.png"],
  48: "",
  49: "",
  50: "",
};
const images_sm_Data = {
  1: "",
  2: "",
  3: "",
  4: "PAG4-1_SM.png",
  5: "PAG5-1_SM.png",
  6: ["PAG6-1_SM.png", "PAG6-2_SM.png"],
  7: "",
  8: "",
  9: "",
  10: ["PAG10-1_SM.png", "PAG10-2_SM.png"],
  11: ["PAG11-1_SM.png", "PAG11-2_SM.png"],
  12: "PAG12-1_SM.png",
  13: ["PAG13-1_SM.png", "PAG13-2_SM.png"],
  14: [
    "PAG14-1_SM.png",
    "PAG14-2_SM.png",
    "PAG14-3_SM.png",
    "PAG14-4_SM.png",
    "PAG14-5_SM.png",
  ],
  15: "PAG15-1_SM.png",
  16: "PAG16-1_SM.png",
  17: "PAG17-1_SM.png",
  18: ["PAG18-1_SM.png", "PAG18-2_SM.png", "PAG18-3_SM.png", "PAG18-4_SM.png"],
  19: "PAG19-1_SM.png",
  20: " ",
  21: [
    "PAG21-1_SM.png",
    "PAG21-2_SM.png",
    "PAG21-3_SM.png",
    "PAG21-4_SM.png",
    "PAG21-5_SM.png",
  ],
  22: "PAG22-1_SM.png",
  23: " ",
  24: "PAG24-1_SM.png",
  25: ["PAG25-1_SM.png", "PAG25-2_SM.png"],
  26: " ",
  27: [
    "PAG27-1_SM.png",
    "PAG27-2_SM.png",
    "PAG27-3_SM.png",
    "PAG27-4_SM.png",
    "PAG27-5_SM.png",
  ],
  28: "PAG28-1_SM.png ",
  29: " ",
  30: " ",
  31: "PAG31-1_SM.png",
  32: ["PAG33-1_SM.png", "PAG33-2_SM.png"],
  33: "PAG34-1_SM.png",
  34: ["PAG35-1_SM.png", "PAG35-2_SM.png"],
  35: " ",
  36: "PAG36-1_SM.png",
  37: "PAG37-1_SM.png ",
  38: "PAG38-1_SM.png ",
  39: "",
  40: "",
  41: "PAG41-1_SM.png",
  42: "PAG42-1_SM.png",
  43: "PAG44-1_SM.png",
  44: "",
  45: [
    "PAG47-1_SM.png",
    "PAG47-2_SM.png",
    "PAG47-3_SM.png",
    "PAG47-4_SM.png",
    "PAG47-5_SM.png",
  ],
  46: "PAG46-1_SM.png",
  47: ["PAG49-1_SM.png", "PAG49-2_SM.png"],
  48: "",
  49: "",
  50: "",
};
const images_md_Data = {
  1: "",
  2: "",
  3: "",
  4: "PAG4-1_MD.png",
  5: "PAG5-1_MD.png",
  6: ["PAG6-1_MD.png", "PAG6-2_MD.png"],
  7: "",
  8: "",
  9: "",
  10: ["PAG10-1_MD.png", "PAG10-2_MD.png"],
  11: ["PAG11-1_MD.png", "PAG11-2_MD.png"],
  12: "PAG12-1_MD.png",
  13: ["PAG13-1_MD.png", "PAG13-2_MD.png"],
  14: [
    "PAG14-1_MD.png",
    "PAG14-2_MD.png",
    "PAG14-3_MD.png",
    "PAG14-4_MD.png",
    "PAG14-5_MD.png",
  ],
  15: "PAG15-1_MD.png",
  16: "PAG16-1_MD.png",
  17: "PAG17-1_MD.png",
  18: ["PAG18-1_MD.png", "PAG18-2_MD.png", "PAG18-3_MD.png", "PAG18-4_MD.png"],
  19: "PAG19-1_MD.png",
  20: " ",
  21: [
    "PAG21-1_MD.png",
    "PAG21-2_MD.png",
    "PAG21-3_MD.png",
    "PAG21-4_MD.png",
    "PAG21-5_MD.png",
  ],
  22: "PAG22-1_MD.png",
  23: " ",
  24: "PAG24-1_MD.png",
  25: ["PAG25-1_MD.png", "PAG25-2_MD.png"],
  26: " ",
  27: [
    "PAG27-1_MD.png",
    "PAG27-2_MD.png",
    "PAG27-3_MD.png",
    "PAG27-4_MD.png",
    "PAG27-5_MD.png",
  ],
  28: "PAG28-1_MD.png ",
  29: " ",
  30: " ",
  31: "PAG31-1_MD.png",
  32: ["PAG33-1_MD.png", "PAG33-2_MD.png"],
  33: "PAG34-1_MD.png",
  34: ["PAG35-1_MD.png", "PAG35-2_MD.png"],
  35: " ",
  36: "PAG36-1_MD.png",
  37: "PAG37-1_MD.png ",
  38: "PAG38-1_MD.png ",
  39: "",
  40: "",
  41: "PAG41-1_MD.png",
  42: "PAG42-1_MD.png",
  43: "PAG44-1_MD.png",
  44: "",
  45: [
    "PAG47-1_MD.png",
    "PAG47-2_MD.png",
    "PAG47-3_MD.png",
    "PAG47-4_MD.png",
    "PAG47-5_MD.png",
  ],
  46: "PAG46-1_MD.png",
  47: ["PAG49-1_MD.png", "PAG49-2_MD.png"],
  48: "",
  49: "",
  50: "",
};
const imagesData = {
  1: "",
  2: "",
  3: "",
  4: "PAG4-1.png",
  5: "PAG5-1.png",
  6: ["PAG6-1.png", "PAG6-2.png"],
  7: "",
  8: "",
  9: "",
  10: ["PAG10-1.png", "PAG10-2.png"],
  11: ["PAG11-1.png", "PAG11-2.png"],
  12: "PAG12-1.png",
  13: ["PAG13-1.png", "PAG13-2.png"],
  14: [
    "PAG14-1.png",
    "PAG14-2.png",
    "PAG14-3.png",
    "PAG14-4.png",
    "PAG14-5.png",
  ],
  15: "PAG15-1.png",
  16: "PAG16-1.png",
  17: "PAG17-1.png",
  18: ["PAG18-1.png", "PAG18-2.png", "PAG18-3.png", "PAG18-4.png"],
  19: "PAG19-1.png",
  20: " ",
  21: [
    "PAG21-1.png",
    "PAG21-2.png",
    "PAG21-3.png",
    "PAG21-4.png",
    "PAG21-5.png",
  ],
  22: "PAG22-1.png",
  23: " ",
  24: "PAG24-1.png",
  25: ["PAG25-1.png", "PAG25-2.png"],
  26: " ",
  27: [
    "PAG27-1.png",
    "PAG27-2.png",
    "PAG27-3.png",
    "PAG27-4.png",
    "PAG27-5.png",
  ],
  28: "PAG28-1.png ",
  29: " ",
  30: " ",
  31: "PAG31-1.png",
  32: ["PAG33-1.png", "PAG33-2.png"],
  33: "PAG34-1.png",
  34: ["PAG35-1.png", "PAG35-2.png"],
  35: " ",
  36: "PAG36-1.png",
  37: "PAG37-1.png ",
  38: "PAG38-1.png ",
  39: "",
  40: "",
  41: "PAG41-1.png",
  42: "PAG42-1.png",
  43: "PAG44-1.png",
  44: "",
  45: [
    "PAG47-1.png",
    "PAG47-2.png",
    "PAG47-3.png",
    "PAG47-4.png",
    "PAG47-5.png",
  ],
  46: "PAG46-1.png",
  47: ["PAG49-1.png", "PAG49-2.png"],
  48: "",
  49: "",
  50: "",
};

const buttonsNameData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: [
    "Actividad de inicio ",
    "Normativa internacional",
    "Normativa nacional",
    "Normativa emitida por el Ministerio de Educación",
    "Actividad Sugerida",
  ],
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: [
    "Actividad de inicio ",
    "Conflicto en el ambito educativo",
    "Características del conflicto",
    "Factores de riesgo y violencia",
    "Actividad Sugerida",
  ],
  13: "",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: [
    "Actividad de inicio ",
    "Enfoque restaurativo",
    "Enfoques punitivo y restaurativo",
    "Principios restaurativos",
    "Actividad Sugerida",
  ],
  34: "",
  35: "",
  36: "",
  37: "",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: "",
  49: "",
  50: "",
};

const buttonsPageNumberData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: [6, 7, 8, 9, 11],
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: [13, 14, 17, 22, 32],
  13: "",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: [34, 35, 37, 41, 47],
  34: "",
  35: "",
  36: "",
  37: "",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: "",
  49: "",
  50: "",
};
const linksData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: "",
  6: "https://docs.google.com/document/d/1279QXm7hHXpcICKyRduFxn11gL_ShQEi/edit?usp=drive_link&ouid=118068284416475194361&rtpof=true&sd=true",
  7: "",
  8: "",
  9: "",
  10: "https://www.ddechuquisaca.gob.bo/app/documentos/PROTOCOLO%20DE%20PREVENCI%C3%93N%20DENUNCIAS%20AGRESIONES%20SEXUALES.pdf",
  11: "https://docs.google.com/document/d/1tdhPdn8Kx4Yp2Z5xlk5irNtZ-MK0zYRa/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  12: "",
  13: "https://docs.google.com/document/d/1DMv56j2fzPCWbXl85iyvxZSSIluFhDZK/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "https://www.oep.org.bo/wp-content/uploads/2023/02/LEY-548-CODIGO-NINIA-NINIO-ADOLESCENTE.pdf",
  26: "",
  // 27: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "https://docs.google.com/document/d/17LBSHrJP1vLnnVrzTLDSMkasGwxl0L5H/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  33: "",
  34: "https://docs.google.com/document/d/1wJCbTq50fWUPVSNioklgPWcpjAx1QqaT/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  35: "",
  36: "",
  37: "",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  //44: "",
  44: "",
  45: "",
  46: "",
  47: "https://docs.google.com/document/d/14zIwR2sDe254Dy6FieMyPY5h5EYYWgi5/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  48: "",
  49: "",
  50: "",
};
